
    create table medicos (
        ativo boolean,
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        crm varchar(255),
        email varchar(255),
        especialidade varchar(255) check (especialidade in ('ORTOPEDIA','CARDIOLOGIA','GINECOLOGIA','NEUROLOGIA','PEDIATRIA','DERMATOLOGIA')),
        logradouro varchar(255),
        nome varchar(255),
        numero varchar(255),
        telefone varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table pacientes (
        ativo boolean,
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        cpf varchar(255),
        email varchar(255),
        logradouro varchar(255),
        nome varchar(255),
        numero varchar(255),
        telefone varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table usuarios (
        id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (id)
    );

    create table consultas (
        data timestamp(6),
        id bigint generated by default as identity,
        medico_id bigint,
        paciente_id bigint,
        primary key (id)
    );

    create table medicos (
        ativo boolean,
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        crm varchar(255),
        email varchar(255),
        especialidade varchar(255) check (especialidade in ('ORTOPEDIA','CARDIOLOGIA','GINECOLOGIA','NEUROLOGIA','PEDIATRIA','DERMATOLOGIA')),
        logradouro varchar(255),
        nome varchar(255),
        numero varchar(255),
        telefone varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table pacientes (
        ativo boolean,
        id bigint generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        cidade varchar(255),
        complemento varchar(255),
        cpf varchar(255),
        email varchar(255),
        logradouro varchar(255),
        nome varchar(255),
        numero varchar(255),
        telefone varchar(255),
        uf varchar(255),
        primary key (id)
    );

    create table usuarios (
        id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (id)
    );

    alter table if exists consultas 
       add constraint FK9ufe3uh84ex5uofhsubaan07m 
       foreign key (medico_id) 
       references medicos;

    alter table if exists consultas 
       add constraint FKe93cdauso5jd1y4bdpox45n4t 
       foreign key (paciente_id) 
       references pacientes;
